### ISSUE TITLE
makeSampple.py doesnt output entire audio

### ISSUE THREAD

**Issue by h-bar-c** [MrBaseband/CocktailParty#1]
Only the first sample seems to be dumped into .wav file

**Comment by h-bar-c** [comment]
Looks like it's something to do with how 'm1' and 'm2' are extracted out from 'results'

**Comment by MrBaseband** [comment]
Some kind of clipping happens for sum or difference > 1. This gets clipped off during audio encoding. Temporary workaround is to ensure that the  W matrix has rows that sum to 1. (Wont work in real-life mixing scenario)
